cache:
  - '%USERPROFILE%\.cargo'
  - target
environment:
  matrix:
    - TARGET: x86_64-pc-windows-msvc
    - TARGET: i686-pc-windows-msvc
    - TARGET: x86_64-pc-windows-gnu
    - TARGET: i686-pc-windows-gnu
  RUST_BACKTRACE: full
branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Enable building pull requests.
    - master
    - v2-master
install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -vV
  - cargo -vV
build: false
test_script:
  - cargo test --all --no-default-features
  - cargo test --all --features "yaml unstable"
notifications:
  - provider: Email
    on_build_success: false
