os: linux
language: rust
cache: cargo
rust: stable
jobs:
  allow_failures:
    - rust: nightly
    - env:
        - SHARD=coverage
  fast_finish: true
  include:
    - os: osx
    - {}
    - rust: 1.36.0
    - rust: beta
    - rust: nightly
    - env:
        - SHARD=lint
      before_script:
        - rustup component add clippy
        - rustup component add rustfmt
      script:
        - echo "Checking codebase with Clippy release `cargo clippy --version`."
        - cargo clippy --all --lib --features "yaml unstable" -- -D warnings
        - cargo clippy --all --tests --examples --features "yaml unstable"
        - cargo fmt -- --check
    - rust: nightly
      env:
        - SHARD=bench
      script:
        - cargo bench
    - env:
        - SHARD=coverage
      addons:
        apt:
          packages:
            - libssl-dev
            - cmake
            - pkg-config
            - zlib1g-dev
          update: true
      before_script:
        - cargo install cargo-tarpaulin
      script:
        - cargo tarpaulin --workspace --features "yaml unstable" --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
script:
  - cargo test --all --no-default-features
  - cargo test --all --features yaml unstable
notifications:
  email: false
env:
  global:
    - secure: JLBlgHY6OEmhJ8woewNJHmuBokTNUv7/WvLkJGV8xk0t6bXBwSU0jNloXwlH7FiQTc4TccX0PumPDD4MrMgxIAVFPmmmlQOCmdpYP4tqZJ8xo189E5zk8lKF5OyaVYCs5SMmFC3cxCsKjfwGIexNu3ck5Uhwe9jI0tqgkgM3URA=
