status = [
	"continuous-integration/travis-ci/push",
	"clap-rs.clap",
	"Tests",
	"Release Profile Tests",
]
pr_status = [
	"continuous-integration/travis-ci/pr",
	"clap-rs.clap",
	"Tests",
	"Release Profile Tests",
]
timeout_sec = 7200
prerun_timeout_sec = 7200
delete_merged_branches = true
cut_body_after = ""
block_lables = ["M: blocked", "M: require changes"]
