[package]

name = "clap"
version = "0.10.3"
authors = ["Kevin K. <kbknapp@gmail.com>"]
exclude = ["examples/*", "clap-tests/*"]
description = "A simple to use, efficient, and full featured  Command Line Argument Parser"
repository = "https://github.com/kbknapp/clap-rs.git"
documentation = "http://kbknapp.github.io/clap-rs"
readme = "README.md"
license = "MIT"
keywords = ["argument", "command", "arg", "parser", "parse"]


[features]
default=["suggestions", "color"]
suggestions=["strsim"]
color = ["ansi_term"]

# for building with nightly and unstable features
unstable=[]

[dependencies.strsim]
version = "*"
optional = true

[dependencies.ansi_term]
version = "*"
optional = true
