[package]
name = "clap"
version = "3.0.0-beta.1"
edition = "2018"
authors = [
	"Kevin K. <kbknapp@gmail.com>",
	"Clap Maintainers"
]
include = [
	"src/**/*",
	"Cargo.toml",
	"README.md"
]
description = "A simple to use, efficient, and full-featured Command Line Argument Parser"
repository = "https://github.com/clap-rs/clap"
documentation = "https://docs.rs/clap/"
homepage = "https://clap.rs/"
keywords = [
	"argument",
	"cli",
	"arg",
	"parser",
	"parse"
]
categories = ["command-line-interface"]
license = "MIT OR Apache-2.0"
readme = "README.md"

[lib]
bench = false

[[bench]]
harness = false
name = "01_default"

[[bench]]
harness = false
name = "02_simple"

[[bench]]
harness = false
name = "03_complex"

[[bench]]
harness = false
name = "04_new_help"

[[bench]]
harness = false
name = "05_ripgrep"

[[bench]]
harness = false
name = "06_rustup"

[badges]
is-it-maintained-issue-resolution = { repository = "clap-rs/clap" }
is-it-maintained-open-issues = { repository = "clap-rs/clap" }
maintenance = {status = "actively-developed"}

[dependencies]
bitflags              = "1.2"
unicode-width         = "0.1"
textwrap              = "0.11"
indexmap              = "1.0"
os_str_bytes          = "2.1"
vec_map               = "0.8"
strsim      = { version = "0.10",  optional = true }
yaml-rust   = { version = "0.4.1",  optional = true }
atty        = { version = "0.2",  optional = true }
termcolor   = { version = "1.1", optional = true }
term_size   = { version = "1.0.0-beta1", optional = true }
lazy_static = { version = "1", optional = true }
clap_derive = { path = "./clap_derive", version = "3.0.0-beta.1", optional = true }

[dev-dependencies]
regex = "1.0"
lazy_static = "1"
version-sync = "0.8"
criterion = { git = "git://github.com/bheisler/criterion.rs", version = "0.3" }

[features]
default     = ["suggestions", "color", "derive", "std", "cargo"]
std         = [] # support for no_std in a backwards-compatible way
suggestions = ["strsim"]
color       = ["atty", "termcolor"]
wrap_help   = ["term_size", "textwrap/term_size"]
derive      = ["clap_derive", "lazy_static"]
yaml        = ["yaml-rust"]
cargo       = [] # Disable if you're not using Cargo, enables Cargo-env-var-dependent macros
unstable    = ["clap_derive/unstable"] # for building with unstable clap features (doesn't require nightly Rust) (currently none)
debug       = ["clap_derive/debug"] # Enables debug messages
doc         = ["yaml"] # All the features which add to documentation

[profile.test]
opt-level = 1

[profile.bench]
lto = true
codegen-units = 1

[package.metadata.docs.rs]
features = ["doc"]
targets = ["x86_64-unknown-linux-gnu"]

[workspace]
members = [
	"clap_derive",
	"clap_generate",
]
default-members = [
	".",
	"clap_derive",
	"clap_generate",
]
