[package]

name = "clap"
version = "1.2.5"
authors = ["Kevin K. <kbknapp@gmail.com>"]
exclude = ["examples/*", "clap-tests/*"]
description = "A simple to use, efficient, and full featured  Command Line Argument Parser"
repository = "https://github.com/kbknapp/clap-rs.git"
documentation = "http://kbknapp.github.io/clap-rs"
readme = "README.md"
license = "MIT"
keywords = ["argument", "command", "arg", "parser", "parse"]

[dependencies.strsim]
version = "~0.4.0"
optional = true

[dependencies.ansi_term]
version = "~0.6.3"
optional = true

#[dependencies.clippy]
#version = "~0.0.12"
#optional = true

[features]
default=["suggestions", "color"]
suggestions=["strsim"]
color = ["ansi_term"]
#lints = ["clippy", "nightly"]

# for building with nightly and unstable features
nightly = []

# for building with travis-cargo
#unstable = ["lints", "nightly"]
unstable = ["nightly"]

# for building with debug messages
debug = []

