[workspace]
members = [
	"clap_derive",
	"clap_generate",
	"clap_generate_fig",
]

[package]
name = "clap"
version = "3.0.0-beta.5"
description = "A simple to use, efficient, and full-featured Command Line Argument Parser"
authors = [
	"Kevin K. <kbknapp@gmail.com>",
	"Clap Maintainers"
]
repository = "https://github.com/clap-rs/clap"
documentation = "https://docs.rs/clap/"
homepage = "https://clap.rs/"
categories = ["command-line-interface"]
keywords = [
	"argument",
	"cli",
	"arg",
	"parser",
	"parse"
]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
include = [
  "build.rs",
  "src/**/*",
  "Cargo.toml",
  "LICENSE*",
  "README.md",
  "benches/**/*",
  "examples/**/*"
]

[package.metadata.docs.rs]
features = ["doc"]

[features]
default = [
	"std",
	"color",
	"suggestions",
]
debug = ["clap_derive/debug", "backtrace"] # Enables debug messages
doc = ["derive", "cargo", "wrap_help", "yaml", "env", "unicode", "regex", "unstable-replace", "unstable-multicall", "unstable-grouped"] # for docs.rs

# Used in default
std = ["indexmap/std"] # support for no_std in a backwards-compatible way
color = ["atty", "termcolor"]
suggestions = ["strsim"]

# Optional
derive = ["clap_derive", "lazy_static"]
cargo = ["lazy_static"] # Disable if you're not using Cargo, enables Cargo-env-var-dependent macros
wrap_help = ["terminal_size", "textwrap/terminal_size"]
yaml = ["yaml-rust"]
env = [] # Use environment variables during arg parsing
unicode = ["textwrap/unicode-width", "unicase"]  # Support for unicode characters in arguments and help messages

# In-work features
unstable-replace = []
unstable-multicall = []
unstable-grouped = []

[lib]
bench = false

[[bench]]
harness = false
name = "01_default"
path = "benches/01_default.rs"

[[bench]]
harness = false
name = "02_simple"
path = "benches/02_simple.rs"

[[bench]]
harness = false
name = "03_complex"
path = "benches/03_complex.rs"

[[bench]]
harness = false
name = "04_new_help"
path = "benches/04_new_help.rs"

[[bench]]
harness = false
name = "05_ripgrep"
path = "benches/05_ripgrep.rs"

[[bench]]
harness = false
name = "06_rustup"
path = "benches/06_rustup.rs"

[dependencies]
clap_derive = { path = "./clap_derive", version = "=3.0.0-beta.5", optional = true }
bitflags = "1.2"
textwrap = { version = "0.14.0", default-features = false, features = [] }
unicase = { version = "2.6", optional = true }
indexmap = "1.0"
os_str_bytes = "5.0"
strsim = { version = "0.10",  optional = true }
yaml-rust = { version = "0.4.1",  optional = true }
atty = { version = "0.2",  optional = true }
termcolor = { version = "1.1", optional = true }
terminal_size = { version = "0.1.12", optional = true }
lazy_static = { version = "1", optional = true }
regex = { version = "1.0", optional = true }
backtrace = { version = "0.3", optional = true }

[dev-dependencies]
regex = "1.0"
lazy_static = "1"
criterion = "0.3.2"
# Cutting out `filesystem` feature
trycmd = { version = "0.8.0", default-features = false, features = ["color-auto", "diff", "examples"] }

[[example]]
name = "busybox"
path = "examples/24a_multicall_busybox.rs"
required-features = ["unstable-multicall"]

[[example]]
name = "hostname"
path = "examples/24b_multicall_hostname.rs"
required-features = ["unstable-multicall"]

[[example]]
name = "09_cargo_metadata"
required-features = ["cargo"]

[[example]]
name = "demo"
required-features = ["derive"]

[profile.test]
opt-level = 1

[profile.bench]
lto = true
codegen-units = 1

