[package]
name = "clap_derive"
version = "3.0.0-beta.1"
edition = "2018"
authors = [
    "Guillaume Pinot <texitoi@texitoi.eu>",
    "Kevin K. <kbknapp@gmail.com>",
    "hoverbear <andrew@hoverbear.org>"
]
description = "Parse command line argument by defining a struct, derive crate."
documentation = "https://docs.rs/clap_derive"
repository = "https://github.com/clap-rs/clap_derive"
keywords = ["clap", "cli", "derive", "proc_macro", "parse"]
categories = ["command-line-interface", "development-tools::procedural-macro-helpers"]
license = "Apache-2.0/MIT"
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1", features = ["full"] }
quote = "1"
proc-macro2 = "1"
heck = "0.3.0"
proc-macro-error = "0.4.3"

[dev-dependencies]
clap = { path = "../", version = "3.0.0-beta.1" }
trybuild = "1.0.5"
rustversion = "1"

[features]
default = []
nightly = []
lints = []
debug = []
doc = []
