name: Bug report
description: Things not quite working right
labels:
   - 'T: bug'
#  - 'C-bug'
#  - 'S-triage'
body:
  - type: checkboxes
    attributes:
      options:
        - label: I have searched the [discussions](https://github.com/clap-rs/clap/discussions)
        - label: I have searched the existing issues
  - type: textarea
    attributes:
      label: Description
    validations:
      required: true
  - type: input
    attributes:
      label: Version
      description: Can be found in Cargo.lock or Cargo.toml of your project (i.e. `grep clap Cargo.lock`). PLEASE DO NOT PUT "latest" HERE, use precise version. Put `master` (or other branch) if you're using the repo directly.
  - type: textarea
    attributes:
      label: Minimal reproducible code
      description: Please write a minimal complete program which has this bug. Do not point to an existing repository.
      value: |
        ```rust
        fn main() {}
        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behaviour
      description: When I do like *this*, *that* is happening and I think it shouldn't.
  - type: textarea
    attributes:
      label: Expected Behaviour
      description: I think *this* should happen instead.
  - type: textarea
    attributes:
      label: Debug Output
      description: |
        Compile clap with `debug` feature:

        ```toml
        [dependencies]
        clap = { version = "*", features = ["debug"] }
        ```
