name: Feature request
description: Suggest an idea for this project
labels:
  - 'C-enchancement'
  - 'C-waiting-on-design'
body:
  - type: checkboxes
    attributes:
      options:
        - label: I have searched the [discussions](https://github.com/clap-rs/clap/discussions)
        - label: I have searched the existing issues
  - type: input
    attributes:
      label: Version
      description: Can be found in Cargo.lock or Cargo.toml of your project (i.e. `grep clap Cargo.lock`). PLEASE DO NOT PUT "latest" HERE, use precise version. Put `master` (or other branch) if you're using the repo directly.
  - type: textarea
    attributes:
      label: Use Case
      description: Describe the problem you're trying to solve.
  - type: textarea
    attributes:
      label: Requirements
      description: Describe what is needed to satisfy your use case.
  - type: textarea
    attributes:
      label: Possible Solutions
      description: A clear and concise description of any solutions or features you've managed to come up with.
