name: Linux
on:
  push:
    branches: [staging, trying]
  pull_request:
    branches: [master]
    types: [opened, reopened, synchronize]
jobs:
  test-release:
    name: Release Profile Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache cargo
        uses: actions/cache@v1
        with:
          path: /home/runner/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --features "yaml unstable"
      - name: Install cargo-cache
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-cache
          use-tool-cache: true
      - name: Cleanup cache
        run: cargo cache -a
