name: Site
on:
  push:
    branches: [master]
    paths: ["site/**"]
jobs:
  site:
    name: Deploy site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: shalzz/zola-deploy-action@master
        env:
          BUILD_DIR: site
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
